// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {usecase} from '../models';
import {menu} from '../models';
import {port} from '../models';

export function CaptureFullscreen():Promise<app.CaptureResult>;

export function CaptureInteractive():Promise<app.CaptureResult>;

export function CaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<app.CaptureResult>;

export function CaptureWindow(arg1:string):Promise<app.CaptureResult>;

export function CheckPermissions():Promise<usecase.PermissionResult>;

export function ConfigureHotkeys(arg1:Array<app.HotkeyBindingInput>):Promise<void>;

export function CopyLastToClipboard():Promise<void>;

export function CreateMenu():Promise<menu.Menu>;

export function ListWindows():Promise<Array<app.WindowInfo>>;

export function LoadConfig():Promise<port.AppConfig>;

export function SaveConfig(arg1:port.AppConfig):Promise<void>;

export function SaveLastScreenshot(arg1:string):Promise<void>;

export function StartRecording(arg1:string):Promise<void>;

export function StartRecordingRegion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<void>;

export function StopRecording():Promise<app.RecordingResult>;
