// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureFullscreen() {
  return window['go']['app']['App']['CaptureFullscreen']();
}

export function CaptureInteractive() {
  return window['go']['app']['App']['CaptureInteractive']();
}

export function CapturePreview() {
  return window['go']['app']['App']['CapturePreview']();
}

export function CaptureRegion(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CaptureRegion'](arg1, arg2, arg3, arg4);
}

export function CaptureScrollable(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CaptureScrollable'](arg1, arg2, arg3, arg4);
}

export function CaptureWindow(arg1) {
  return window['go']['app']['App']['CaptureWindow'](arg1);
}

export function CheckPermissions() {
  return window['go']['app']['App']['CheckPermissions']();
}

export function ConfigureHotkeys(arg1) {
  return window['go']['app']['App']['ConfigureHotkeys'](arg1);
}

export function CopyLastToClipboard() {
  return window['go']['app']['App']['CopyLastToClipboard']();
}

export function CreateMenu() {
  return window['go']['app']['App']['CreateMenu']();
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function ListRecordingSources() {
  return window['go']['app']['App']['ListRecordingSources']();
}

export function ListWindows() {
  return window['go']['app']['App']['ListWindows']();
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function Notify(arg1, arg2) {
  return window['go']['app']['App']['Notify'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenPermissionsSettings() {
  return window['go']['app']['App']['OpenPermissionsSettings']();
}

export function PermissionsReady() {
  return window['go']['app']['App']['PermissionsReady']();
}

export function RequestAccessibility() {
  return window['go']['app']['App']['RequestAccessibility']();
}

export function RequestCamera() {
  return window['go']['app']['App']['RequestCamera']();
}

export function RequestMicrophone() {
  return window['go']['app']['App']['RequestMicrophone']();
}

export function RequestScreenCapture() {
  return window['go']['app']['App']['RequestScreenCapture']();
}

export function RevealFile(arg1) {
  return window['go']['app']['App']['RevealFile'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveDir() {
  return window['go']['app']['App']['SaveDir']();
}

export function SaveLastScreenshot(arg1) {
  return window['go']['app']['App']['SaveLastScreenshot'](arg1);
}

export function SetWindowAsBar() {
  return window['go']['app']['App']['SetWindowAsBar']();
}

export function SetWindowAsMain() {
  return window['go']['app']['App']['SetWindowAsMain']();
}

export function SetWindowAsOverlay() {
  return window['go']['app']['App']['SetWindowAsOverlay']();
}

export function StartRecording(arg1) {
  return window['go']['app']['App']['StartRecording'](arg1);
}

export function StopRecording() {
  return window['go']['app']['App']['StopRecording']();
}

export function UpdateLastScreenshot(arg1) {
  return window['go']['app']['App']['UpdateLastScreenshot'](arg1);
}
