// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {usecase} from '../models';
import {app} from '../models';
import {port} from '../models';

export function CaptureFullscreen():Promise<entity.Screenshot>;

export function CaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<entity.Screenshot>;

export function CaptureWindow(arg1:string):Promise<entity.Screenshot>;

export function CheckPermissions():Promise<usecase.PermissionResult>;

export function ConfigureHotkeys(arg1:Array<app.HotkeyBindingInput>):Promise<void>;

export function CopyToClipboard(arg1:Array<number>):Promise<void>;

export function ListWindows():Promise<Array<app.WindowInfo>>;

export function LoadConfig():Promise<port.AppConfig>;

export function SaveConfig(arg1:port.AppConfig):Promise<void>;

export function SaveScreenshotToFile(arg1:string):Promise<void>;

export function StartRecording(arg1:string):Promise<void>;

export function StartRecordingRegion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<void>;

export function StopRecording():Promise<entity.Recording>;
