// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {usecase} from '../models';
import {menu} from '../models';
import {port} from '../models';

export function CaptureFullscreen():Promise<app.CaptureResult>;

export function CaptureInteractive():Promise<app.CaptureResult>;

export function CapturePreview():Promise<app.CaptureResult>;

export function CaptureRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<app.CaptureResult>;

export function CaptureScrollable(arg1:number,arg2:number,arg3:number,arg4:number):Promise<app.CaptureResult>;

export function CaptureWindow(arg1:string):Promise<app.CaptureResult>;

export function CheckPermissions():Promise<usecase.PermissionResult>;

export function ConfigureHotkeys(arg1:Array<app.HotkeyBindingInput>):Promise<void>;

export function CopyLastToClipboard():Promise<void>;

export function CreateMenu():Promise<menu.Menu>;

export function HideWindow():Promise<void>;

export function ListRecordingSources():Promise<app.RecordingSources>;

export function ListWindows():Promise<Array<app.WindowInfo>>;

export function LoadConfig():Promise<port.AppConfig>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenPermissionsSettings():Promise<void>;

export function PermissionsReady():Promise<boolean>;

export function RequestAccessibility():Promise<void>;

export function RequestCamera():Promise<void>;

export function RequestMicrophone():Promise<void>;

export function RequestScreenCapture():Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveConfig(arg1:port.AppConfig):Promise<void>;

export function SaveDir():Promise<string>;

export function SaveLastScreenshot(arg1:string):Promise<void>;

export function SetWindowAsBar():Promise<void>;

export function SetWindowAsMain():Promise<void>;

export function SetWindowAsOverlay():Promise<void>;

export function StartRecording(arg1:string):Promise<void>;

export function StopRecording():Promise<void>;
